[package]
name = "kyepb/benefitroleplay"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@1.7.0"
Avalog = "imavafe/avalog@0.1.8"

[server-dependencies]
ProfileStore = "vyon/profilestore@1.0.3"